[web]
  port = 8910
  apiProxyPath = "/api/functions"

[api]
  port = 8911
  schemaPath = "./api/db/schema.prisma"
  [api.paths]
  functions = './api/src/functions'
  graphql = './api/src/graphql'
  generated = './api/generated'
